apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  destinations:
  - namespace: staging
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
