apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-chatbot-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/giridharan-official/ai-chatbot-infra.git
    targetRevision: main
    path: gitops/app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/giridharan-official/*'
  destinations:
    - namespace: 'dev'
      server: 'https://kubernetes.default.svc'
    - namespace: 'staging'
      server: 'https://kubernetes.default.svc'
    - namespace: 'prod'
      server: 'https://kubernetes.default.svc'
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
