apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-chatbot-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/giridharan-official/ai-chatbot-infra.git
    targetRevision: main
    path: gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
